services:
  # Notification Application
  urlaubsplanung-notification:
    build:
      context: .
      dockerfile: Dockerfile
    image: hiiico/vacation_planning-urlaubsplanung-notification  # Add this line for pushing
    ports:
      - "8081:8081"
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=${MYSQL_HOST}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      # Kafka Configuration
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      # email configuration
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
      - SPRING_MAIL_PROTOCOL=smtp
    networks:
      - app-network
    depends_on:
      kafka:
        condition: service_started
      mysql-db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
  kafka_data:
    driver: local
  mysql_data:
    driver: local
